// Simple translation bundle for Cook14U
// Exposes `window.__cook14u_translations` with per-language dictionaries
(function(){
    window.__cook14u_translations = {
        en: {
            section_content: 'Content',
            section_about: 'About',
            section_community: 'Community',
            section_merch: 'Merch/Support',
            join_cook14u: 'Join Cook14U',
            open_instagram: 'Open Instagram post',
            navbar_logo_alt: 'Cook14U logo',
            codmunity_btn: 'CODmunity',
            wzmeta_btn: 'WZ Meta',
            tools_btn: 'Tracker',
            nav_home: 'Home',
            nav_content: 'Content',
            nav_about: 'About',
            nav_community: 'Community',
            nav_merch: 'Merch/Support',
            lang_label: 'EN',
            lang_title: 'Change language',
            demo_on: 'Demo: ON',
            demo_off: 'Demo: OFF',
            live_online_title: 'Cook14U is LIVE — click to open Twitch',
            live_offline_title: 'Offline — click to open Discord (or open community)',
            open_setup: 'SHOW SETUP',
            home_subtext: 'Welcome to my community! Join us for fun gaming.',
            home_subtext_html: 'Welcome to the community!<br>please Join us for <br>Yappin<br>Banter<br>and Gaming',
            option_twitch_main: 'Twitch Live',
            option_twitch_sub: 'Live stream',
            option_youtube_main: 'YouTube Playlist',
            option_youtube_sub: 'Playlist slideshow',
            option_instagram_main: 'Instagram',
            option_instagram_sub: 'Selected feed',
            option_tiktok_main: 'TikTok Feed',
            option_tiktok_sub: 'Latest posts',
            content_link_open: 'Open',
            modal_setup_title: 'My Setup',
            about_paragraph_html: "I'm a lifelong gamer, I started streaming on <a href=\"https://twitch.tv/cook14u\" target=\"_blank\" rel=\"noopener\">Twitch.tv/cook14u</a> just to be able to watch my gameplay in hopes of improving... It turned into this growing community I am very much blessed to be a part of. Mostly on Warzone but I play some of mostly everything... There's some laughs, there's some pains, but mostly the channel revolves around self reflecting to improve.",
            setup_gaming: 'Gaming:',
            setup_monitor: 'Monitor:',
            setup_audio: 'Audio:',
            setup_streaming: 'Streaming:',
            setup_mic: 'Mic:',
            setup_camera: 'Camera:',
            close_label: 'Close',
            footer_credit: 'Made by Tom Lamers - 2025',
            wzmeta_title: 'Warzone Meta App',
            codtracker_title: 'COD Tracker',
            codmunity_title: 'CODmunity'
        },
        es: {
            section_content: 'Contenido',
            section_about: 'Acerca',
            section_community: 'Comunidad',
            section_merch: 'Tienda/Soporte',
            join_cook14u: 'Únete a Cook14U',
            open_instagram: 'Abrir publicación de Instagram',
            navbar_logo_alt: 'logotipo de Cook14U',
            codmunity_btn: 'CODmunity',
            wzmeta_btn: 'WZ Meta',
            tools_btn: 'Rastreador',
            nav_home: 'Inicio',
            nav_content: 'Contenido',
            nav_about: 'Acerca',
            nav_community: 'Comunidad',
            nav_merch: 'Tienda/Soporte',
            lang_label: 'ES',
            lang_title: 'Cambiar idioma',
            demo_on: 'Demo: ON',
            demo_off: 'Demo: OFF',
            live_online_title: 'Cook14U está EN VIVO — haz clic para abrir Twitch',
            live_offline_title: 'Sin conexión — haz clic para abrir Discord (o abrir comunidad)',
            open_setup: 'MOSTRAR CONFIGURACIÓN',
            home_subtext: '¡Bienvenido a mi comunidad! Únete para jugar y pasar un buen rato.',
            home_subtext_html: '¡Bienvenido a la comunidad!<br>Por favor únete a nosotros para<br>Dale que dale<br>Chingueo<br>y Gaming',
            option_twitch_main: 'Twitch en vivo',
            option_twitch_sub: 'Transmisión en vivo',
            option_youtube_main: 'Lista de YouTube',
            option_youtube_sub: 'Presentación de lista',
            option_instagram_main: 'Instagram',
            option_instagram_sub: 'Feed seleccionado',
            option_tiktok_main: 'TikTok',
            option_tiktok_sub: 'Últimas publicaciones',
            content_link_open: 'Abrir',
            modal_setup_title: 'Mi Configuración',
            about_paragraph_html: "Soy un jugador de toda la vida. Empecé a hacer streaming en <a href=\"https://twitch.tv/cook14u\" target=\"_blank\" rel=\"noopener\">Twitch.tv/cook14u</a> para poder ver mis partidas y así mejorar... Se convirtió en esta comunidad en crecimiento de la que me siento muy agradecido. Principalmente juego Warzone, pero juego de todo un poco... Hay risas, hay momentos duros, pero el canal gira en torno a la reflexión personal para mejorar.",
            setup_gaming: 'Juego:',
            setup_monitor: 'Monitor:',
            setup_audio: 'Audio:',
            setup_streaming: 'Streaming:',
            setup_mic: 'Micrófono:',
            setup_camera: 'Cámara:',
            close_label: 'Cerrar',
            footer_credit: 'Hecho por Tom Lamers - 2025',
            wzmeta_title: 'Aplicación Warzone Meta',
            codtracker_title: 'Rastreador COD',
            codmunity_title: 'CODmunity'
        }
    };
    // default language preference — can be overridden from localStorage
    window.__cook14u_lang = localStorage.getItem('cook14u_lang') || 'en';
})();
